import asyncio
from playwright.async_api import async_playwright

SEEDS = list(range(37, 47))

BASE_URL = "https://sanand0.github.io/tdsdata/js_table/?seed={}"


async def scrape():
    grand_total = 0

    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()

        for seed in SEEDS:
            url = BASE_URL.format(seed)
            print(f"\nVisiting: {url}")

            await page.goto(url)

            # VERY IMPORTANT: tables are generated by JavaScript
            await page.wait_for_selector("table")

            # Extract all numbers from all tables
            numbers = await page.eval_on_selector_all(
                "table td",
                """cells => cells
                    .map(cell => parseFloat(cell.innerText))
                    .filter(n => !isNaN(n))
                """
            )

            page_sum = sum(numbers)
            print(f"Seed {seed} sum: {page_sum}")

            grand_total += page_sum

        print("\n=====================================")
        print("FINAL TOTAL:", grand_total)
        print("=====================================\n")

        await browser.close()


if __name__ == "__main__":
    asyncio.run(scrape())